In [1]:
import pandas as pd
import numpy as np

data = pd.read_csv(r'ml-100k\u.data',sep = "\t", header = None)
item = pd.read_csv(r'ml-100k\u.item' , encoding = 'latin1' ,sep = "|",header = None)
user = pd.read_csv(r'ml-100k\u.user'  , encoding = 'latin1',sep = "|",header = None)
base = pd.read_csv(r'ml-100k\ua.base'  ,sep = "\t", header = None)
test = pd.read_csv(r'ml-100k\ua.test'  ,sep = "\t", header = None)

In [2]:
rate_train = base.to_numpy()
rate_test = test.to_numpy()

r_cols = ['user_id', 'movie_id', 'rating', 'unix_timestamp']
base.columns = r_cols
test.columns = r_cols

i_cols = ['movie id', 'movie title' ,'release date','video release date', 'IMDb URL', 'unknown', 'Action', 'Adventure',
 'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']

item.columns = i_cols

X0 = item.to_numpy()
X_train_counts = X0[:,5:]



In [3]:
from sklearn.feature_extraction.text import TfidfTransformer
transformer = TfidfTransformer(smooth_idf=True, norm ='l2')

tfidf = transformer.fit_transform(X_train_counts.tolist()).toarray()

In [4]:
def get_items_rated_by_user(rate_matrix, user_id):
    condition = rate_matrix[:, 0] == user_id
    item_ids = (rate_matrix[condition][:,1]) -1
    scores = (rate_matrix[condition][:,2])
    return item_ids, scores

In [102]:
a,b = get_items_rated_by_user(rate_test, 2)

In [107]:
a

array([ 12,  49, 250, 279, 280, 289, 291, 296, 311, 313], dtype=int64)

In [ ]:
tfidf[a, :].shape

(10, 19)

: 

In [119]:
item.to_clipboard()

In [117]:
 0.5339**2 + 0.84551629**2

0.9999470066553641

In [5]:
user.shape

(943, 5)

In [7]:
from sklearn.linear_model import Ridge
from sklearn import linear_model

n_users = user.shape[0]

d = tfidf.shape[1] 
W = np.zeros((d, n_users))
b = np.zeros((1, n_users))




In [8]:
ids,scores = get_items_rated_by_user(rate_train,user_id= 3)
Xhat = tfidf[ids, :]
clf = Ridge(alpha=0.01, fit_intercept  = True)
clf.fit(Xhat, scores) 

Ridge(alpha=0.01)

In [11]:
Xhat.shape

(44, 19)

In [ ]:
scores.shape

(44,)

: 

In [95]:
rate_matrix

array([[        1,         1,         5, 874965758],
       [        1,         2,         3, 876893171],
       [        1,         3,         4, 878542960],
       ...,
       [      943,      1188,         3, 888640250],
       [      943,      1228,         3, 888640275],
       [      943,      1330,         3, 888692465]], dtype=int64)

In [125]:
X0[3,:]
print(tfidf[:,3])

[0.74066017 0.         0.         ... 0.         0.         0.        ]


In [133]:
tfidf.shape

(1682, 19)

In [132]:
tfidf[:,3].shape

(1682,)

In [131]:
np.sum(tfidf[:,3]**2)

21.537906466815695

In [ ]:
tfidf[3,]

(array([135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147,
        148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160,
        161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173,
        174], dtype=int64),)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 1, 1, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=object)

In [54]:
X0

array([[1, 'Toy Story (1995)', '01-Jan-1995', ..., 0, 0, 0],
       [2, 'GoldenEye (1995)', '01-Jan-1995', ..., 1, 0, 0],
       [3, 'Four Rooms (1995)', '01-Jan-1995', ..., 1, 0, 0],
       ...,
       [1680, 'Sliding Doors (1998)', '01-Jan-1998', ..., 0, 0, 0],
       [1681, 'You So Crazy (1994)', '01-Jan-1994', ..., 0, 0, 0],
       [1682, 'Scream of Stone (Schrei aus Stein) (1991)', '08-Mar-1996',
        ..., 0, 0, 0]], dtype=object)